"""多灾种风险评估报告生成器（片B）。

职责：把 coverage_analysis 引擎直连 / LLM 全链返回的 stats 落盘为
三语 Markdown 风险评估报告，并输出阈值预警信息。

红线合规：
- 零新依赖（仅标准库）
- 不改引擎 / guards / 现有模板 / CRS / 注册表
- 输出目录固定为 <项目根>/user_data/reports/
"""

from __future__ import annotations

import datetime
import os
from typing import Any, Dict, Optional

# ── 项目根（与 disaster_registry 同规则：src/core/.. -> 项目根） ──
_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
REPORTS_DIR = os.path.join(_PROJECT_ROOT, "user_data", "reports")

# 覆盖率预警阈值（百分比）：低于该值触发预警
WARNING_THRESHOLD = 50.0

# ── 三语文案（report_generator 独立内置，不依赖 i18n 模块） ──
_TEXTS: Dict[str, Dict[str, str]] = {
    "zh": {
        "title": "多灾种风险评估报告",
        "generated_at": "生成时间",
        "disaster": "灾种",
        "source_layer": "源图层（避难所）",
        "boundary_layer": "危险区图层",
        "stats": "覆盖统计",
        "source_count": "源要素数",
        "radius_m": "缓冲半径 (m)",
        "total_area": "危险区总面积 (m²)",
        "covered_area": "覆盖面积 (m²)",
        "coverage_rate": "覆盖率",
        "warning_title": "覆盖率预警",
        "warning_msg": "「{disaster}」危险区覆盖率仅为 {rate}%，低于预警阈值 {threshold}%，建议核查避难所布点。",
        "note": "说明",
        "note_text": "本报告由 AIQGIS 多灾种风险评估模块自动生成，覆盖率基于避难所缓冲范围与危险区面积之比。",
        "user_text": "用户指令",
    },
    "ja": {
        "title": "多災種リスク評価レポート",
        "generated_at": "生成日時",
        "disaster": "災種",
        "source_layer": "ソースレイヤ（避難所）",
        "boundary_layer": "危険区域レイヤ",
        "stats": "カバー統計",
        "source_count": "ソース地物数",
        "radius_m": "バッファ半径 (m)",
        "total_area": "危険区域総面積 (m²)",
        "covered_area": "カバー面積 (m²)",
        "coverage_rate": "カバー率",
        "warning_title": "カバー率警告",
        "warning_msg": "「{disaster}」の危険区域カバー率はわずか {rate}% で、警告閾値 {threshold}% を下回っています。避難所の配置を確認することをお勧めします。",
        "note": "備考",
        "note_text": "本レポートは AIQGIS 多災種リスク評価モジュールにより自動生成され、カバー率は避難所バッファ範囲と危険区域面積の比率に基づきます。",
        "user_text": "ユーザー指示",
    },
    "en": {
        "title": "Multi-Disaster Risk Assessment Report",
        "generated_at": "Generated At",
        "disaster": "Disaster",
        "source_layer": "Source Layer (Shelters)",
        "boundary_layer": "Hazard Zone Layer",
        "stats": "Coverage Statistics",
        "source_count": "Source Feature Count",
        "radius_m": "Buffer Radius (m)",
        "total_area": "Hazard Zone Total Area (m²)",
        "covered_area": "Covered Area (m²)",
        "coverage_rate": "Coverage Rate",
        "warning_title": "Coverage Warning",
        "warning_msg": "\"{disaster}\" hazard-zone coverage is only {rate}%, below the warning threshold {threshold}%. Review shelter placement.",
        "note": "Note",
        "note_text": "This report is auto-generated by the AIQGIS multi-disaster risk assessment module. Coverage is the ratio of shelter-buffer area to hazard-zone area.",
        "user_text": "User Instruction",
    },
}


def _t(lang: str, key: str) -> str:
    return _TEXTS.get(lang, _TEXTS["zh"]).get(key, _TEXTS["zh"].get(key, key))


def generate_report(
    disaster_id: str,
    stats: Dict[str, Any],
    source_layer: str = "",
    boundary_layer: str = "",
    lang: str = "zh",
    user_text: str = "",
    threshold: float = WARNING_THRESHOLD,
) -> Dict[str, Any]:
    """根据覆盖率统计生成三语 Markdown 风险评估报告。

    Parameters
    ----------
    disaster_id : str
        灾种注册 ID（earthquake/flood/landslide/wildfire）。
    stats : dict
        coverage_analysis 返回的统计：source_count / radius_m /
        total_area / covered_area / coverage_rate。
    source_layer / boundary_layer : str
        参与分析的图层名（缺省显示为 "-"）。
    lang : str
        zh / ja / en。
    user_text : str
        触发本次分析的用户指令（可为空）。
    threshold : float
        覆盖率预警阈值（百分比）。

    Returns
    -------
    dict
        {"success": bool, "report_path": str, "warning": str,
         "disaster_name": str, "coverage_rate": float}
        warning 为空表示未触发预警。
    """
    from core.disaster_registry import get_disaster, get_disaster_name, get_risk_zone_layer

    info = get_disaster(disaster_id) or {}
    disaster_name = get_disaster_name(disaster_id, lang)
    if not stats or "coverage_rate" not in stats:
        return {
            "success": False,
            "report_path": "",
            "warning": "",
            "disaster_name": disaster_name,
            "coverage_rate": None,
        }

    coverage_rate = float(stats["coverage_rate"])
    rate_display = f"{coverage_rate:.4f}"
    # 覆盖率 < 阈值（默认 50%）时预警
    warning_msg = ""
    if coverage_rate < threshold:
        warning_msg = _t(lang, "warning_msg").format(
            disaster=disaster_name,
            rate=f"{coverage_rate:.2f}",
            threshold=f"{threshold:.2f}",
        )

    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    stamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    os.makedirs(REPORTS_DIR, exist_ok=True)
    report_path = os.path.join(REPORTS_DIR, f"risk_report_{stamp}_{disaster_id}.md")

    src = source_layer or "-"
    bnd = boundary_layer or get_risk_zone_layer(disaster_id) or "-"
    radius = stats.get("radius_m", "-")
    total_area = stats.get("total_area", "-")
    covered_area = stats.get("covered_area", "-")
    source_count = stats.get("source_count", "-")

    lines: list[str] = []
    lines.append(f"# {_t(lang, 'title')}")
    lines.append("")
    lines.append(f"- **{_t(lang, 'generated_at')}**: {ts}")
    lines.append(f"- **{_t(lang, 'disaster')}**: {disaster_name} (`{disaster_id}`)")
    lines.append(f"- **{_t(lang, 'source_layer')}**: {src}")
    lines.append(f"- **{_t(lang, 'boundary_layer')}**: {bnd}")
    if user_text:
        lines.append(f"- **{_t(lang, 'user_text')}**: {user_text}")
    lines.append("")
    lines.append(f"## {_t(lang, 'stats')}")
    lines.append("")
    lines.append(f"| {_t(lang, 'source_count')} | {_t(lang, 'radius_m')} | {_t(lang, 'total_area')} | {_t(lang, 'covered_area')} | {_t(lang, 'coverage_rate')} |")
    lines.append("| --- | --- | --- | --- | --- |")
    lines.append(f"| {source_count} | {radius} | {total_area} | {covered_area} | **{rate_display}%** |")
    lines.append("")
    if warning_msg:
        lines.append(f"## {_t(lang, 'warning_title')}")
        lines.append("")
        lines.append(f"> ⚠️ {warning_msg}")
        lines.append("")
    lines.append(f"### {_t(lang, 'note')}")
    lines.append("")
    lines.append(_t(lang, "note_text"))
    lines.append("")

    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return {
        "success": True,
        "report_path": report_path,
        "warning": warning_msg,
        "disaster_name": disaster_name,
        "coverage_rate": coverage_rate,
    }
